### ISSUE TITLE
Upcoming PR TODO

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gibct-data-service#191]
- [x] Complaints Roll-up
- [x] Adjust error line number in Loader
- [x] Rename USE_COLUMN to something more descriptive
- [x] Dashboard
- [x] Export Institution table
- [x] Uploads Tracking model
- [x] Uploads Crontroller/Views
- [x] Add number converter to remove d,ddd,ddd type numbers from csvs...
